version: '3'
services:
  web:
    build: .
    tty: true
    container_name: openldap
    environment:
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_DOMAIN=example.org
      - LDAP_ORGANISATION=Example Inc.
    networks:
      - ldap_nw
    ports:
      - "389:389"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - '/srv/ldap:/var/lib/ldap'
networks:
  ldap_nw:
    external: true
